export default [
    {
        name: "Bootstrap",
        color: "#2b6dff",
        nameID: "bootstrap",
        assets: "/icons/bootstrap.svg",
    },
    {
        name: "Css",
        color: "#20c928",
        nameID: "css",
        assets: "/icons/css.svg",
    },
    {
        name: "Express",
        color: "#d41cf1",
        nameID: "express",
        assets: "/icons/express.svg",
    },
    {
        name: "Git",
        color: "#ef2350",
        nameID: "git",
        assets: "/icons/git.svg",
    },
    {
        name: "Html",
        color: "#ff36a2",
        nameID: "html",
        assets: "/icons/html.svg",
    },
    {
        name: "Javascript",
        color: "#5345f7",
        nameID: "js",
        assets: "/icons/js.svg",
    },
    {
        name: "Mongo DB",
        color: "#ffaa1b",
        nameID: "mongo",
        assets: "/icons/mongo.svg",
    },
    {
        name: "Next Js",
        color: "#8935ff",
        nameID: "next",
        assets: "/icons/next.svg",
    },
    {
        name: "Node Js",
        color: "#ff006e",
        nameID: "node",
        assets: "/icons/node.svg",
    },
    {
        name: "Postgresql",
        color: "#00a1ff",
        nameID: "postgres",
        assets: "/icons/postgres.svg",
    },
    {
        name: "React Js",
        color: "#f97316",
        nameID: "react",
        assets: "/icons/react.svg",
    },
    {
        name: "Sql",
        color: "#6366f1",
        nameID: "sql",
        assets: "/icons/sql.svg",
    },
    {
        name: "Tailwind",
        color: "#21c95f",
        nameID: "tailwind",
        assets: "/icons/tailwind.svg",
    },
    {
        name: "Vite",
        color: "#8D71FE",
        nameID: "vite",
        assets: "/icons/vite.svg",
    },
    {
        name: "Wordpress",
        color: "#0077b6",
        nameID: "wordpress",
        assets: "/icons/wordpress.svg",
    },
];
